const data = [
  {
    fullName: "Bertha Mee",
    gender: "Female",
    jobTitle: "Chief Design Engineer",
    language: "Yiddish",
    ssn: "891-28-5502",
    money: "$502.81",
  },
  {
    fullName: "Royal Poore",
    gender: "Male",
    jobTitle: "Research Assistant II",
    language: "Maltese",
    ssn: "251-85-8836",
    money: "$379.74",
  },
  {
    fullName: "Merwin O'Hannigan",
    gender: "Male",
    jobTitle: "Human Resources Assistant II",
    language: "Bengali",
    ssn: "357-40-6012",
    money: "$218.68",
  },
  {
    fullName: "Giorgio Botright",
    gender: "Male",
    jobTitle: "Recruiting Manager",
    language: "Bulgarian",
    ssn: "518-43-1317",
    money: "$12.27",
  },
  {
    fullName: "Adelheid Roddy",
    gender: "Female",
    jobTitle: "Analog Circuit Design manager",
    language: "English",
    ssn: "802-81-4529",
    money: "$724.52",
  },
  {
    fullName: "Tony Barrack",
    gender: "Female",
    jobTitle: "Operator",
    language: "Maltese",
    ssn: "589-83-4536",
    money: "$690.26",
  },
  {
    fullName: "Alfonso Poel",
    gender: "Male",
    jobTitle: "Paralegal",
    language: "Swati",
    ssn: "602-45-1891",
    money: "$838.79",
  },
  {
    fullName: "Roley Cashell",
    gender: "Male",
    jobTitle: "Staff Accountant II",
    language: "Albanian",
    ssn: "800-45-6765",
    money: "$202.70",
  },
  {
    fullName: "Iago Spacey",
    gender: "Male",
    jobTitle: "Product Engineer",
    language: "Hebrew",
    ssn: "371-17-5782",
    money: "$957.57",
  },
  {
    fullName: "Lutero Iaduccelli",
    gender: "Male",
    jobTitle: "Administrative Assistant II",
    language: "Hindi",
    ssn: "398-08-9122",
    money: "$159.55",
  },
  {
    fullName: "Giacobo Toquet",
    gender: "Male",
    jobTitle: "Account Representative I",
    language: "New Zealand Sign Language",
    ssn: "813-89-4061",
    money: "$931.74",
  },
  {
    fullName: "Carleton Franzolini",
    gender: "Male",
    jobTitle: "Mechanical Systems Engineer",
    language: "Finnish",
    ssn: "552-93-8343",
    money: "$82.75",
  },
  {
    fullName: "Lesya Toller",
    gender: "Female",
    jobTitle: "Health Coach III",
    language: "Papiamento",
    ssn: "311-83-4850",
    money: "$164.82",
  },
  {
    fullName: "Janifer Judkins",
    gender: "Female",
    jobTitle: "Executive Secretary",
    language: "Bosnian",
    ssn: "371-36-1501",
    money: "$498.16",
  },
  {
    fullName: "Ameline Van der Baaren",
    gender: "Female",
    jobTitle: "Nurse Practicioner",
    language: "Tsonga",
    ssn: "674-55-4547",
    money: "$961.41",
  },
  {
    fullName: "Arline Yaakov",
    gender: "Female",
    jobTitle: "Editor",
    language: "Gujarati",
    ssn: "698-51-3889",
    money: "$814.05",
  },
  {
    fullName: "Hebert Handford",
    gender: "Male",
    jobTitle: "Accounting Assistant I",
    language: "Yiddish",
    ssn: "264-59-0696",
    money: "$924.22",
  },
  {
    fullName: "Aime Peacocke",
    gender: "Female",
    jobTitle: "Chief Design Engineer",
    language: "Albanian",
    ssn: "807-36-0700",
    money: "$934.83",
  },
  {
    fullName: "Agneta Edbrooke",
    gender: "Female",
    jobTitle: "Marketing Assistant",
    language: "Zulu",
    ssn: "674-64-3357",
    money: "$554.89",
  },
  {
    fullName: "Randolph Benadette",
    gender: "Male",
    jobTitle: "Cost Accountant",
    language: "Gagauz",
    ssn: "569-88-7085",
    money: "$395.76",
  },
  {
    fullName: "Lief Ratter",
    gender: "Male",
    jobTitle: "Registered Nurse",
    language: "Swati",
    ssn: "732-76-5163",
    money: "$731.46",
  },
  {
    fullName: "Bran Kirimaa",
    gender: "Male",
    jobTitle: "Account Representative IV",
    language: "Kazakh",
    ssn: "755-31-1702",
    money: "$708.07",
  },
  {
    fullName: "Colver Greated",
    gender: "Male",
    jobTitle: "Account Coordinator",
    language: "Yiddish",
    ssn: "281-20-6291",
    money: "$841.48",
  },
  {
    fullName: "Howey Dolan",
    gender: "Male",
    jobTitle: "Structural Engineer",
    language: "Tok Pisin",
    ssn: "504-38-5399",
    money: "$988.08",
  },
  {
    fullName: "Omero Gantley",
    gender: "Male",
    jobTitle: "Staff Accountant IV",
    language: "Albanian",
    ssn: "407-16-4295",
    money: "$292.71",
  },
  {
    fullName: "Heywood Rapsey",
    gender: "Male",
    jobTitle: "Office Assistant IV",
    language: "Dari",
    ssn: "641-68-3111",
    money: "$590.37",
  },
  {
    fullName: "Evangelin Sugg",
    gender: "Female",
    jobTitle: "Financial Advisor",
    language: "Azeri",
    ssn: "289-31-1116",
    money: "$605.90",
  },
  {
    fullName: "Montague Apple",
    gender: "Male",
    jobTitle: "Structural Analysis Engineer",
    language: "German",
    ssn: "712-36-8645",
    money: "$417.57",
  },
  {
    fullName: "Gilemette Lowres",
    gender: "Female",
    jobTitle: "Computer Systems Analyst II",
    language: "Montenegrin",
    ssn: "330-74-8408",
    money: "$1.37",
  },
  {
    fullName: "Vincents Tenpenny",
    gender: "Male",
    jobTitle: "Dental Hygienist",
    language: "Hindi",
    ssn: "813-57-5933",
    money: "$63.44",
  },
  {
    fullName: "Bernardo Kersaw",
    gender: "Male",
    jobTitle: "Librarian",
    language: "Spanish",
    ssn: "760-34-8740",
    money: "$744.51",
  },
  {
    fullName: "Debora Worsnap",
    gender: "Female",
    jobTitle: "Tax Accountant",
    language: "Bengali",
    ssn: "505-76-3052",
    money: "$294.70",
  },
  {
    fullName: "Darrin Sidey",
    gender: "Male",
    jobTitle: "Quality Engineer",
    language: "Maltese",
    ssn: "888-58-0353",
    money: "$919.77",
  },
  {
    fullName: "Thadeus Aspden",
    gender: "Male",
    jobTitle: "VP Quality Control",
    language: "German",
    ssn: "802-86-6916",
    money: "$356.10",
  },
  {
    fullName: "Thurstan Helsby",
    gender: "Male",
    jobTitle: "VP Marketing",
    language: "Kashmiri",
    ssn: "223-58-1033",
    money: "$83.36",
  },
  {
    fullName: "Haywood Gannaway",
    gender: "Male",
    jobTitle: "Occupational Therapist",
    language: "Gagauz",
    ssn: "824-35-6951",
    money: "$444.45",
  },
  {
    fullName: "Avery Burkart",
    gender: "Male",
    jobTitle: "VP Quality Control",
    language: "Indonesian",
    ssn: "664-07-3509",
    money: "$467.81",
  },
  {
    fullName: "Flint Lethibridge",
    gender: "Male",
    jobTitle: "Associate Professor",
    language: "Dari",
    ssn: "750-15-2223",
    money: "$879.45",
  },
  {
    fullName: "Benetta Locker",
    gender: "Female",
    jobTitle: "Health Coach III",
    language: "Belarusian",
    ssn: "663-27-6748",
    money: "$295.29",
  },
  {
    fullName: "Ferdy Folks",
    gender: "Male",
    jobTitle: "Director of Sales",
    language: "Pashto",
    ssn: "333-08-4690",
    money: "$323.82",
  },
  {
    fullName: "Beverlee Minchell",
    gender: "Female",
    jobTitle: "Accounting Assistant IV",
    language: "Catalan",
    ssn: "664-11-5968",
    money: "$206.22",
  },
  {
    fullName: "Wes McNirlan",
    gender: "Male",
    jobTitle: "Web Designer II",
    language: "Gagauz",
    ssn: "198-06-2415",
    money: "$936.92",
  },
  {
    fullName: "Bendick Sephton",
    gender: "Male",
    jobTitle: "Senior Financial Analyst",
    language: "Dutch",
    ssn: "638-71-9932",
    money: "$249.86",
  },
  {
    fullName: "Ade Wildbore",
    gender: "Male",
    jobTitle: "Mechanical Systems Engineer",
    language: "Bosnian",
    ssn: "490-22-3232",
    money: "$984.09",
  },
  {
    fullName: "Danila Tillett",
    gender: "Female",
    jobTitle: "Statistician IV",
    language: "Greek",
    ssn: "580-69-1722",
    money: "$418.02",
  },
  {
    fullName: "Leon Jeannequin",
    gender: "Male",
    jobTitle: "Product Engineer",
    language: "Afrikaans",
    ssn: "105-56-9409",
    money: "$190.94",
  },
  {
    fullName: "Markus Eblein",
    gender: "Male",
    jobTitle: "Recruiting Manager",
    language: "Fijian",
    ssn: "463-31-8743",
    money: "$204.67",
  },
  {
    fullName: "Franklin Meni",
    gender: "Male",
    jobTitle: "Senior Developer",
    language: "Papiamento",
    ssn: "619-43-9005",
    money: "$191.45",
  },
  {
    fullName: "Pace Gwyllt",
    gender: "Male",
    jobTitle: "Civil Engineer",
    language: "Burmese",
    ssn: "383-45-9539",
    money: "$610.85",
  },
  {
    fullName: "Charlie Staveley",
    gender: "Male",
    jobTitle: "Tax Accountant",
    language: "Guaraní",
    ssn: "742-56-4944",
    money: "$235.16",
  },
  {
    fullName: "Bradford Brehat",
    gender: "Male",
    jobTitle: "Developer III",
    language: "Aymara",
    ssn: "371-83-9089",
    money: "$695.21",
  },
  {
    fullName: "Brennan Powell",
    gender: "Male",
    jobTitle: "Database Administrator I",
    language: "Bislama",
    ssn: "846-38-2056",
    money: "$217.87",
  },
  {
    fullName: "Jennica Haxby",
    gender: "Female",
    jobTitle: "Automation Specialist III",
    language: "Tamil",
    ssn: "287-20-0500",
    money: "$479.35",
  },
  {
    fullName: "Lorens Djurevic",
    gender: "Male",
    jobTitle: "Accountant II",
    language: "Hiri Motu",
    ssn: "279-19-6442",
    money: "$577.04",
  },
  {
    fullName: "Elysha Billing",
    gender: "Female",
    jobTitle: "Desktop Support Technician",
    language: "Kannada",
    ssn: "739-52-4548",
    money: "$761.05",
  },
  {
    fullName: "Marcelline Jagiello",
    gender: "Female",
    jobTitle: "Budget/Accounting Analyst III",
    language: "Māori",
    ssn: "368-85-0650",
    money: "$566.25",
  },
  {
    fullName: "Gerome Basset",
    gender: "Male",
    jobTitle: "Biostatistician IV",
    language: "Montenegrin",
    ssn: "201-87-6904",
    money: "$278.13",
  },
  {
    fullName: "Bette Crapper",
    gender: "Female",
    jobTitle: "Actuary",
    language: "Irish Gaelic",
    ssn: "145-76-7422",
    money: "$933.98",
  },
  {
    fullName: "Shannen Summerbell",
    gender: "Female",
    jobTitle: "Administrative Officer",
    language: "Thai",
    ssn: "115-23-2898",
    money: "$238.50",
  },
  {
    fullName: "Bondie Plowell",
    gender: "Male",
    jobTitle: "Nurse Practicioner",
    language: "Assamese",
    ssn: "439-10-5779",
    money: "$467.86",
  },
  {
    fullName: "Addison Poile",
    gender: "Male",
    jobTitle: "VP Quality Control",
    language: "Montenegrin",
    ssn: "821-67-0006",
    money: "$890.52",
  },
  {
    fullName: "Garrett Hazelby",
    gender: "Male",
    jobTitle: "Design Engineer",
    language: "Zulu",
    ssn: "700-43-2724",
    money: "$15.61",
  },
  {
    fullName: "Kristofor McClymond",
    gender: "Male",
    jobTitle: "Computer Systems Analyst IV",
    language: "Georgian",
    ssn: "424-75-0326",
    money: "$849.32",
  },
  {
    fullName: "Merna Taye",
    gender: "Female",
    jobTitle: "Human Resources Assistant I",
    language: "Swati",
    ssn: "474-04-6119",
    money: "$914.90",
  },
  {
    fullName: "Titos Dickings",
    gender: "Male",
    jobTitle: "Senior Editor",
    language: "Arabic",
    ssn: "736-45-6998",
    money: "$274.69",
  },
  {
    fullName: "Anselm Malling",
    gender: "Male",
    jobTitle: "Assistant Manager",
    language: "Estonian",
    ssn: "887-69-3552",
    money: "$322.57",
  },
  {
    fullName: "Paige Crocumbe",
    gender: "Female",
    jobTitle: "Associate Professor",
    language: "Polish",
    ssn: "276-86-7342",
    money: "$239.38",
  },
  {
    fullName: "Granger Please",
    gender: "Male",
    jobTitle: "Environmental Specialist",
    language: "Lao",
    ssn: "186-51-0797",
    money: "$547.14",
  },
  {
    fullName: "Caressa Browncey",
    gender: "Female",
    jobTitle: "Electrical Engineer",
    language: "Kazakh",
    ssn: "265-89-9644",
    money: "$384.89",
  },
  {
    fullName: "Taite Ingliby",
    gender: "Male",
    jobTitle: "Executive Secretary",
    language: "Gagauz",
    ssn: "429-82-7952",
    money: "$333.98",
  },
  {
    fullName: "Mendy Torre",
    gender: "Male",
    jobTitle: "Automation Specialist IV",
    language: "Chinese",
    ssn: "581-47-2480",
    money: "$560.54",
  },
  {
    fullName: "Raynard Shillabeare",
    gender: "Male",
    jobTitle: "Structural Analysis Engineer",
    language: "Ndebele",
    ssn: "286-91-4287",
    money: "$735.36",
  },
  {
    fullName: "Ambrosio Martinolli",
    gender: "Male",
    jobTitle: "Senior Developer",
    language: "Italian",
    ssn: "753-42-6773",
    money: "$353.42",
  },
  {
    fullName: "Brendan Hofer",
    gender: "Male",
    jobTitle: "Data Coordinator",
    language: "Pashto",
    ssn: "722-52-7572",
    money: "$955.62",
  },
  {
    fullName: "Kerk Kennon",
    gender: "Male",
    jobTitle: "Design Engineer",
    language: "Assamese",
    ssn: "768-09-3707",
    money: "$269.81",
  },
  {
    fullName: "Kacy Zannuto",
    gender: "Female",
    jobTitle: "Software Test Engineer IV",
    language: "Sotho",
    ssn: "192-32-0171",
    money: "$488.68",
  },
  {
    fullName: "Smitty Peck",
    gender: "Male",
    jobTitle: "Senior Editor",
    language: "Papiamento",
    ssn: "867-05-0928",
    money: "$791.19",
  },
  {
    fullName: "Cello Antrobus",
    gender: "Male",
    jobTitle: "Teacher",
    language: "Tajik",
    ssn: "399-39-1517",
    money: "$987.60",
  },
  {
    fullName: "Eliot Pardi",
    gender: "Male",
    jobTitle: "Structural Analysis Engineer",
    language: "Tetum",
    ssn: "315-09-9209",
    money: "$476.50",
  },
  {
    fullName: "Rosabel Kincaid",
    gender: "Female",
    jobTitle: "Civil Engineer",
    language: "Greek",
    ssn: "492-20-8913",
    money: "$669.04",
  },
  {
    fullName: "Jay Insworth",
    gender: "Male",
    jobTitle: "Physical Therapy Assistant",
    language: "Azeri",
    ssn: "351-44-2685",
    money: "$197.76",
  },
  {
    fullName: "Dale Tomasicchio",
    gender: "Female",
    jobTitle: "Dental Hygienist",
    language: "Arabic",
    ssn: "140-11-6791",
    money: "$564.05",
  },
  {
    fullName: "Jesus Skeermor",
    gender: "Male",
    jobTitle: "Technical Writer",
    language: "Papiamento",
    ssn: "100-48-7295",
    money: "$968.72",
  },
  {
    fullName: "Bradney Pietersen",
    gender: "Male",
    jobTitle: "Senior Cost Accountant",
    language: "Pashto",
    ssn: "626-34-3230",
    money: "$547.21",
  },
  {
    fullName: "Miriam Yabsley",
    gender: "Female",
    jobTitle: "Help Desk Operator",
    language: "Bosnian",
    ssn: "399-42-2779",
    money: "$675.41",
  },
  {
    fullName: "Culley Tissington",
    gender: "Male",
    jobTitle: "Senior Editor",
    language: "Malagasy",
    ssn: "772-92-2396",
    money: "$578.89",
  },
  {
    fullName: "Husein Guidoni",
    gender: "Male",
    jobTitle: "Food Chemist",
    language: "New Zealand Sign Language",
    ssn: "157-84-3268",
    money: "$583.75",
  },
  {
    fullName: "Aubry Akhurst",
    gender: "Female",
    jobTitle: "Assistant Media Planner",
    language: "Romanian",
    ssn: "413-68-3645",
    money: "$72.14",
  },
  {
    fullName: "Bevvy O'Flaherty",
    gender: "Female",
    jobTitle: "Assistant Manager",
    language: "Bulgarian",
    ssn: "560-83-5458",
    money: "$774.32",
  },
  {
    fullName: "Candra McMichan",
    gender: "Female",
    jobTitle: "Geologist I",
    language: "Kannada",
    ssn: "890-25-2416",
    money: "$848.38",
  },
  {
    fullName: "Tory Bilborough",
    gender: "Female",
    jobTitle: "Information Systems Manager",
    language: "Yiddish",
    ssn: "870-58-5704",
    money: "$692.01",
  },
  {
    fullName: "Eloise Pumphreys",
    gender: "Female",
    jobTitle: "Administrative Officer",
    language: "Latvian",
    ssn: "117-86-2508",
    money: "$662.55",
  },
  {
    fullName: "Selma Geldart",
    gender: "Female",
    jobTitle: "Chemical Engineer",
    language: "Dutch",
    ssn: "214-93-3819",
    money: "$177.96",
  },
  {
    fullName: "Beckie Sutherby",
    gender: "Female",
    jobTitle: "Mechanical Systems Engineer",
    language: "Albanian",
    ssn: "868-19-6208",
    money: "$908.08",
  },
  {
    fullName: "Deena Alman",
    gender: "Female",
    jobTitle: "Junior Executive",
    language: "Tajik",
    ssn: "287-36-5916",
    money: "$70.51",
  },
  {
    fullName: "Francklin Kamiyama",
    gender: "Male",
    jobTitle: "Pharmacist",
    language: "Malagasy",
    ssn: "662-67-0365",
    money: "$464.03",
  },
  {
    fullName: "Bianka Rainsdon",
    gender: "Female",
    jobTitle: "Technical Writer",
    language: "Irish Gaelic",
    ssn: "440-05-7269",
    money: "$740.77",
  },
  {
    fullName: "Xymenes McTrustie",
    gender: "Male",
    jobTitle: "Speech Pathologist",
    language: "Icelandic",
    ssn: "174-65-3067",
    money: "$776.38",
  },
  {
    fullName: "Norma Probate",
    gender: "Female",
    jobTitle: "Quality Control Specialist",
    language: "Dari",
    ssn: "303-35-6452",
    money: "$72.51",
  },
  {
    fullName: "Zacherie Gerling",
    gender: "Male",
    jobTitle: "Developer III",
    language: "Tswana",
    ssn: "245-56-4467",
    money: "$230.23",
  },
  {
    fullName: "Zachary Wigsell",
    gender: "Male",
    jobTitle: "Payment Adjustment Coordinator",
    language: "Moldovan",
    ssn: "879-51-5761",
    money: "$428.10",
  },
  {
    fullName: "Burg Kingaby",
    gender: "Male",
    jobTitle: "Professor",
    language: "Dzongkha",
    ssn: "152-60-4498",
    money: "$537.00",
  },
  {
    fullName: "Rockwell Nuzzetti",
    gender: "Male",
    jobTitle: "Research Assistant I",
    language: "Dari",
    ssn: "660-22-8887",
    money: "$798.99",
  },
  {
    fullName: "Elicia Sandell",
    gender: "Female",
    jobTitle: "Structural Engineer",
    language: "Norwegian",
    ssn: "831-91-0945",
    money: "$475.63",
  },
  {
    fullName: "Liesa Farny",
    gender: "Female",
    jobTitle: "Environmental Tech",
    language: "Thai",
    ssn: "457-93-5757",
    money: "$240.82",
  },
  {
    fullName: "Claudia Duffill",
    gender: "Female",
    jobTitle: "Design Engineer",
    language: "Armenian",
    ssn: "734-61-1934",
    money: "$733.19",
  },
  {
    fullName: "Kayla Vannoni",
    gender: "Female",
    jobTitle: "Chief Design Engineer",
    language: "Guaraní",
    ssn: "490-97-3707",
    money: "$729.15",
  },
  {
    fullName: "Benedikt Avarne",
    gender: "Male",
    jobTitle: "Paralegal",
    language: "Italian",
    ssn: "410-07-2059",
    money: "$438.24",
  },
  {
    fullName: "Lotta Crump",
    gender: "Female",
    jobTitle: "Business Systems Development Analyst",
    language: "Yiddish",
    ssn: "702-46-6384",
    money: "$265.29",
  },
  {
    fullName: "Sullivan Bointon",
    gender: "Male",
    jobTitle: "Health Coach I",
    language: "Kannada",
    ssn: "552-96-2784",
    money: "$861.43",
  },
  {
    fullName: "Lisha Quin",
    gender: "Female",
    jobTitle: "Paralegal",
    language: "Indonesian",
    ssn: "851-15-4223",
    money: "$413.06",
  },
  {
    fullName: "Rafi Seleway",
    gender: "Male",
    jobTitle: "VP Marketing",
    language: "Bengali",
    ssn: "322-37-0638",
    money: "$680.54",
  },
  {
    fullName: "Margarette Rowesby",
    gender: "Female",
    jobTitle: "Accountant I",
    language: "Gagauz",
    ssn: "287-93-8673",
    money: "$975.02",
  },
  {
    fullName: "Robinet Lannen",
    gender: "Male",
    jobTitle: "Budget/Accounting Analyst IV",
    language: "Nepali",
    ssn: "787-71-2488",
    money: "$674.34",
  },
  {
    fullName: "Phillipp Dawes",
    gender: "Male",
    jobTitle: "Web Developer III",
    language: "Tsonga",
    ssn: "830-28-7418",
    money: "$994.64",
  },
  {
    fullName: "Jodie Tapton",
    gender: "Female",
    jobTitle: "Account Coordinator",
    language: "Dari",
    ssn: "698-18-8935",
    money: "$349.91",
  },
  {
    fullName: "Rahel Bridgstock",
    gender: "Female",
    jobTitle: "Senior Financial Analyst",
    language: "Dhivehi",
    ssn: "367-56-3121",
    money: "$131.64",
  },
  {
    fullName: "Alvis Eyden",
    gender: "Male",
    jobTitle: "Dental Hygienist",
    language: "Somali",
    ssn: "855-89-1687",
    money: "$829.78",
  },
  {
    fullName: "Alair Mathivet",
    gender: "Male",
    jobTitle: "Help Desk Technician",
    language: "Guaraní",
    ssn: "365-69-4514",
    money: "$322.59",
  },
  {
    fullName: "Corrianne Trevain",
    gender: "Female",
    jobTitle: "Software Consultant",
    language: "Hungarian",
    ssn: "329-78-4710",
    money: "$423.46",
  },
  {
    fullName: "Josefina Boggers",
    gender: "Female",
    jobTitle: "Marketing Assistant",
    language: "Hiri Motu",
    ssn: "556-32-6173",
    money: "$39.30",
  },
  {
    fullName: "Renaldo Sandercroft",
    gender: "Male",
    jobTitle: "Human Resources Assistant I",
    language: "Albanian",
    ssn: "647-98-5256",
    money: "$326.52",
  },
  {
    fullName: "Foss Bowling",
    gender: "Male",
    jobTitle: "Budget/Accounting Analyst IV",
    language: "Hebrew",
    ssn: "559-25-1657",
    money: "$910.33",
  },
  {
    fullName: "Erroll Conerding",
    gender: "Male",
    jobTitle: "Health Coach II",
    language: "Dutch",
    ssn: "569-77-0071",
    money: "$471.01",
  },
  {
    fullName: "Loutitia Surmeyer",
    gender: "Female",
    jobTitle: "Compensation Analyst",
    language: "Kyrgyz",
    ssn: "760-80-6279",
    money: "$314.26",
  },
  {
    fullName: "Edwina Coldridge",
    gender: "Female",
    jobTitle: "Information Systems Manager",
    language: "Irish Gaelic",
    ssn: "560-81-5499",
    money: "$793.50",
  },
  {
    fullName: "Florence Trigwell",
    gender: "Female",
    jobTitle: "Executive Secretary",
    language: "Burmese",
    ssn: "364-43-4561",
    money: "$513.33",
  },
  {
    fullName: "Mirabel Statton",
    gender: "Female",
    jobTitle: "Staff Accountant I",
    language: "Italian",
    ssn: "779-21-5140",
    money: "$559.83",
  },
  {
    fullName: "Arch Yegorovnin",
    gender: "Male",
    jobTitle: "Sales Associate",
    language: "Albanian",
    ssn: "175-29-6419",
    money: "$673.59",
  },
  {
    fullName: "Doreen Oseland",
    gender: "Female",
    jobTitle: "Graphic Designer",
    language: "Assamese",
    ssn: "635-90-3503",
    money: "$283.36",
  },
  {
    fullName: "Alejoa Antrobus",
    gender: "Male",
    jobTitle: "Programmer IV",
    language: "Swahili",
    ssn: "861-92-5612",
    money: "$443.06",
  },
  {
    fullName: "Randall Fittes",
    gender: "Male",
    jobTitle: "Internal Auditor",
    language: "Czech",
    ssn: "664-93-3429",
    money: "$526.02",
  },
  {
    fullName: "Latia Ferreli",
    gender: "Female",
    jobTitle: "Structural Engineer",
    language: "Yiddish",
    ssn: "727-41-3707",
    money: "$406.36",
  },
  {
    fullName: "Matthaeus Soda",
    gender: "Male",
    jobTitle: "Junior Executive",
    language: "Croatian",
    ssn: "232-85-9001",
    money: "$853.84",
  },
  {
    fullName: "Rollin Stanfield",
    gender: "Male",
    jobTitle: "Environmental Tech",
    language: "Czech",
    ssn: "459-62-6066",
    money: "$591.94",
  },
  {
    fullName: "Alvie Grunbaum",
    gender: "Male",
    jobTitle: "Clinical Specialist",
    language: "Kurdish",
    ssn: "514-61-4151",
    money: "$536.41",
  },
  {
    fullName: "Kippar Pearcy",
    gender: "Male",
    jobTitle: "Programmer II",
    language: "Portuguese",
    ssn: "711-50-9691",
    money: "$441.90",
  },
  {
    fullName: "Galvan McCrow",
    gender: "Male",
    jobTitle: "Business Systems Development Analyst",
    language: "Lithuanian",
    ssn: "344-37-7649",
    money: "$798.17",
  },
  {
    fullName: "Morse Hargrove",
    gender: "Male",
    jobTitle: "Assistant Media Planner",
    language: "Tajik",
    ssn: "165-76-2730",
    money: "$411.08",
  },
  {
    fullName: "Marsiella Joutapavicius",
    gender: "Female",
    jobTitle: "Project Manager",
    language: "Albanian",
    ssn: "447-06-4606",
    money: "$749.90",
  },
  {
    fullName: "Jaine Harle",
    gender: "Female",
    jobTitle: "Speech Pathologist",
    language: "Finnish",
    ssn: "304-69-0356",
    money: "$494.20",
  },
  {
    fullName: "Caz Catanheira",
    gender: "Male",
    jobTitle: "Administrative Officer",
    language: "Croatian",
    ssn: "342-99-8104",
    money: "$844.75",
  },
  {
    fullName: "Austin Landsberg",
    gender: "Female",
    jobTitle: "Executive Secretary",
    language: "Guaraní",
    ssn: "581-55-2770",
    money: "$33.06",
  },
  {
    fullName: "Cicily Szymon",
    gender: "Female",
    jobTitle: "Graphic Designer",
    language: "Dari",
    ssn: "537-68-2984",
    money: "$630.12",
  },
  {
    fullName: "Cloris Rafter",
    gender: "Female",
    jobTitle: "Tax Accountant",
    language: "Haitian Creole",
    ssn: "673-83-6630",
    money: "$143.81",
  },
  {
    fullName: "Brendin Pears",
    gender: "Male",
    jobTitle: "Senior Cost Accountant",
    language: "Montenegrin",
    ssn: "547-48-0582",
    money: "$382.51",
  },
  {
    fullName: "Barbette Mecchi",
    gender: "Female",
    jobTitle: "Social Worker",
    language: "French",
    ssn: "696-90-8036",
    money: "$123.48",
  },
  {
    fullName: "Red Leatherbarrow",
    gender: "Male",
    jobTitle: "Chemical Engineer",
    language: "Afrikaans",
    ssn: "137-67-7970",
    money: "$790.82",
  },
  {
    fullName: "Derwin Getch",
    gender: "Male",
    jobTitle: "Quality Control Specialist",
    language: "Swahili",
    ssn: "590-82-7838",
    money: "$343.01",
  },
  {
    fullName: "Nick Chomiszewski",
    gender: "Male",
    jobTitle: "Geological Engineer",
    language: "English",
    ssn: "560-02-8177",
    money: "$212.61",
  },
  {
    fullName: "Liana Duferie",
    gender: "Female",
    jobTitle: "Budget/Accounting Analyst II",
    language: "Gagauz",
    ssn: "714-01-6086",
    money: "$825.20",
  },
  {
    fullName: "Mill Wapplington",
    gender: "Male",
    jobTitle: "Payment Adjustment Coordinator",
    language: "Swedish",
    ssn: "668-87-7108",
    money: "$366.23",
  },
  {
    fullName: "Kerwin Di Claudio",
    gender: "Male",
    jobTitle: "Dental Hygienist",
    language: "Filipino",
    ssn: "753-28-7270",
    money: "$998.37",
  },
  {
    fullName: "Peyter Northcott",
    gender: "Male",
    jobTitle: "Structural Engineer",
    language: "Amharic",
    ssn: "571-37-0371",
    money: "$614.10",
  },
  {
    fullName: "Payton Jeacop",
    gender: "Male",
    jobTitle: "Civil Engineer",
    language: "Moldovan",
    ssn: "659-21-9529",
    money: "$693.07",
  },
  {
    fullName: "Tommie Driscoll",
    gender: "Male",
    jobTitle: "Software Test Engineer III",
    language: "Persian",
    ssn: "672-21-4139",
    money: "$14.08",
  },
  {
    fullName: "Murial Dusting",
    gender: "Female",
    jobTitle: "Data Coordinator",
    language: "West Frisian",
    ssn: "586-81-0167",
    money: "$76.96",
  },
  {
    fullName: "Cordie Burgiss",
    gender: "Female",
    jobTitle: "Registered Nurse",
    language: "Quechua",
    ssn: "865-11-7191",
    money: "$23.81",
  },
  {
    fullName: "Dorey Pavlov",
    gender: "Female",
    jobTitle: "Account Coordinator",
    language: "West Frisian",
    ssn: "448-12-2432",
    money: "$129.23",
  },
  {
    fullName: "Stanton Oyley",
    gender: "Male",
    jobTitle: "Civil Engineer",
    language: "Norwegian",
    ssn: "829-61-3057",
    money: "$33.66",
  },
  {
    fullName: "Muffin Cochran",
    gender: "Female",
    jobTitle: "Accounting Assistant II",
    language: "Aymara",
    ssn: "183-84-1833",
    money: "$76.67",
  },
  {
    fullName: "Chad Chaperling",
    gender: "Male",
    jobTitle: "Structural Analysis Engineer",
    language: "Ndebele",
    ssn: "510-91-1988",
    money: "$654.98",
  },
  {
    fullName: "Ellen Verrills",
    gender: "Female",
    jobTitle: "Help Desk Technician",
    language: "Amharic",
    ssn: "748-06-4508",
    money: "$117.21",
  },
  {
    fullName: "Glenda McLeoid",
    gender: "Female",
    jobTitle: "Developer IV",
    language: "Filipino",
    ssn: "596-95-3457",
    money: "$282.63",
  },
  {
    fullName: "Cherianne Berndtssen",
    gender: "Female",
    jobTitle: "Community Outreach Specialist",
    language: "Māori",
    ssn: "660-13-6383",
    money: "$839.36",
  },
  {
    fullName: "Briny Crate",
    gender: "Female",
    jobTitle: "Clinical Specialist",
    language: "Korean",
    ssn: "750-63-4332",
    money: "$453.25",
  },
  {
    fullName: "Fonzie Vittery",
    gender: "Male",
    jobTitle: "VP Product Management",
    language: "Polish",
    ssn: "792-38-1849",
    money: "$703.25",
  },
  {
    fullName: "Dasi Gohn",
    gender: "Female",
    jobTitle: "Professor",
    language: "Arabic",
    ssn: "119-88-0108",
    money: "$426.61",
  },
  {
    fullName: "Cherilynn Mackelworth",
    gender: "Female",
    jobTitle: "Graphic Designer",
    language: "Korean",
    ssn: "218-17-4580",
    money: "$737.15",
  },
  {
    fullName: "Lyda Kinsley",
    gender: "Female",
    jobTitle: "Staff Scientist",
    language: "Kyrgyz",
    ssn: "888-34-6203",
    money: "$130.09",
  },
  {
    fullName: "Mahmud Hollebon",
    gender: "Male",
    jobTitle: "Safety Technician I",
    language: "Telugu",
    ssn: "155-79-4105",
    money: "$750.89",
  },
  {
    fullName: "Amalee Huddleston",
    gender: "Female",
    jobTitle: "Paralegal",
    language: "Zulu",
    ssn: "770-15-6232",
    money: "$220.04",
  },
  {
    fullName: "Bordie Antliff",
    gender: "Male",
    jobTitle: "VP Marketing",
    language: "Kazakh",
    ssn: "676-06-2854",
    money: "$571.53",
  },
  {
    fullName: "Scarlet Trethowan",
    gender: "Female",
    jobTitle: "Data Coordinator",
    language: "Norwegian",
    ssn: "538-28-8723",
    money: "$306.96",
  },
  {
    fullName: "Ediva Sidle",
    gender: "Female",
    jobTitle: "Marketing Assistant",
    language: "Polish",
    ssn: "396-76-6267",
    money: "$386.32",
  },
  {
    fullName: "Dyann Brazener",
    gender: "Female",
    jobTitle: "Research Nurse",
    language: "Korean",
    ssn: "203-12-1627",
    money: "$986.54",
  },
  {
    fullName: "Brunhilda Crossgrove",
    gender: "Female",
    jobTitle: "Accountant I",
    language: "Malay",
    ssn: "204-09-6427",
    money: "$825.60",
  },
  {
    fullName: "Freddy Skotcher",
    gender: "Male",
    jobTitle: "Programmer Analyst II",
    language: "Punjabi",
    ssn: "108-40-0796",
    money: "$585.23",
  },
  {
    fullName: "Shaun Sidwick",
    gender: "Female",
    jobTitle: "Account Representative II",
    language: "Somali",
    ssn: "268-96-1446",
    money: "$131.68",
  },
  {
    fullName: "Barrett Fernely",
    gender: "Male",
    jobTitle: "Quality Engineer",
    language: "Sotho",
    ssn: "550-38-0422",
    money: "$293.25",
  },
  {
    fullName: "Galina McKane",
    gender: "Female",
    jobTitle: "Mechanical Systems Engineer",
    language: "Lithuanian",
    ssn: "431-71-5109",
    money: "$436.53",
  },
  {
    fullName: "Kilian McElory",
    gender: "Male",
    jobTitle: "Assistant Manager",
    language: "Portuguese",
    ssn: "522-02-6970",
    money: "$824.84",
  },
  {
    fullName: "Hynda Richold",
    gender: "Female",
    jobTitle: "Community Outreach Specialist",
    language: "Malagasy",
    ssn: "784-56-8214",
    money: "$257.65",
  },
  {
    fullName: "Rowland Petrovykh",
    gender: "Male",
    jobTitle: "Registered Nurse",
    language: "Bulgarian",
    ssn: "354-48-6824",
    money: "$635.36",
  },
  {
    fullName: "Brendon Starking",
    gender: "Male",
    jobTitle: "Research Associate",
    language: "Malagasy",
    ssn: "462-02-1279",
    money: "$362.48",
  },
  {
    fullName: "Bennett Caplis",
    gender: "Male",
    jobTitle: "Developer III",
    language: "Romanian",
    ssn: "243-02-4259",
    money: "$226.34",
  },
  {
    fullName: "Patrica Durrell",
    gender: "Female",
    jobTitle: "Project Manager",
    language: "Moldovan",
    ssn: "370-79-3979",
    money: "$298.81",
  },
  {
    fullName: "Emelita Vynoll",
    gender: "Female",
    jobTitle: "Technical Writer",
    language: "Estonian",
    ssn: "707-14-7770",
    money: "$429.81",
  },
  {
    fullName: "Lanae Barstow",
    gender: "Female",
    jobTitle: "Associate Professor",
    language: "Bulgarian",
    ssn: "101-31-9375",
    money: "$515.41",
  },
  {
    fullName: "Jackqueline Como",
    gender: "Female",
    jobTitle: "General Manager",
    language: "Indonesian",
    ssn: "667-89-3640",
    money: "$332.27",
  },
  {
    fullName: "Emyle Chatfield",
    gender: "Female",
    jobTitle: "Database Administrator IV",
    language: "Swahili",
    ssn: "637-73-5352",
    money: "$55.97",
  },
  {
    fullName: "Averell Mosley",
    gender: "Male",
    jobTitle: "Senior Financial Analyst",
    language: "Hebrew",
    ssn: "229-17-5523",
    money: "$604.80",
  },
  {
    fullName: "Lothario Dunstone",
    gender: "Male",
    jobTitle: "Nurse Practicioner",
    language: "Marathi",
    ssn: "338-28-4541",
    money: "$569.17",
  },
  {
    fullName: "Sigvard McCole",
    gender: "Male",
    jobTitle: "Chemical Engineer",
    language: "Danish",
    ssn: "543-77-0391",
    money: "$550.19",
  },
  {
    fullName: "Felita Ber",
    gender: "Female",
    jobTitle: "Database Administrator I",
    language: "German",
    ssn: "108-80-8032",
    money: "$911.67",
  },
  {
    fullName: "Jemie Latty",
    gender: "Female",
    jobTitle: "Software Engineer IV",
    language: "West Frisian",
    ssn: "773-29-3561",
    money: "$917.02",
  },
  {
    fullName: "Yard O' Lone",
    gender: "Male",
    jobTitle: "Software Test Engineer II",
    language: "Italian",
    ssn: "576-34-4437",
    money: "$247.59",
  },
  {
    fullName: "Delaney Heyburn",
    gender: "Male",
    jobTitle: "Administrative Officer",
    language: "Tamil",
    ssn: "445-04-5749",
    money: "$872.82",
  },
  {
    fullName: "Kelley McElwee",
    gender: "Male",
    jobTitle: "Assistant Manager",
    language: "New Zealand Sign Language",
    ssn: "616-26-0706",
    money: "$958.55",
  },
  {
    fullName: "Glory Ferrieres",
    gender: "Female",
    jobTitle: "VP Accounting",
    language: "Luxembourgish",
    ssn: "276-97-4804",
    money: "$392.16",
  },
  {
    fullName: "Filbert Snellman",
    gender: "Male",
    jobTitle: "Teacher",
    language: "Korean",
    ssn: "843-54-7436",
    money: "$327.43",
  },
  {
    fullName: "Dietrich Le Huquet",
    gender: "Male",
    jobTitle: "Quality Engineer",
    language: "Korean",
    ssn: "613-49-0429",
    money: "$24.30",
  },
  {
    fullName: "Edee Eliyahu",
    gender: "Female",
    jobTitle: "Safety Technician III",
    language: "Norwegian",
    ssn: "622-39-0524",
    money: "$902.89",
  },
  {
    fullName: "Cassondra Georgelin",
    gender: "Female",
    jobTitle: "Computer Systems Analyst III",
    language: "New Zealand Sign Language",
    ssn: "899-17-3431",
    money: "$148.46",
  },
  {
    fullName: "Lorilee Bruck",
    gender: "Female",
    jobTitle: "Senior Editor",
    language: "Hebrew",
    ssn: "394-61-0048",
    money: "$989.72",
  },
  {
    fullName: "Beryle Brunsden",
    gender: "Female",
    jobTitle: "Information Systems Manager",
    language: "Somali",
    ssn: "229-82-2788",
    money: "$615.45",
  },
  {
    fullName: "Maurizia Bridewell",
    gender: "Female",
    jobTitle: "Quality Engineer",
    language: "Northern Sotho",
    ssn: "466-22-1822",
    money: "$766.39",
  },
  {
    fullName: "Devondra Browne",
    gender: "Female",
    jobTitle: "Junior Executive",
    language: "Oriya",
    ssn: "762-21-9013",
    money: "$123.26",
  },
  {
    fullName: "Janeen Loxton",
    gender: "Female",
    jobTitle: "Web Designer III",
    language: "Kyrgyz",
    ssn: "604-80-6228",
    money: "$858.19",
  },
  {
    fullName: "Pincas Spiers",
    gender: "Male",
    jobTitle: "Sales Associate",
    language: "Swedish",
    ssn: "176-82-6901",
    money: "$500.96",
  },
  {
    fullName: "Toddy Coultass",
    gender: "Male",
    jobTitle: "Paralegal",
    language: "Romanian",
    ssn: "776-18-0188",
    money: "$919.77",
  },
  {
    fullName: "Ericha Coales",
    gender: "Female",
    jobTitle: "Food Chemist",
    language: "Thai",
    ssn: "649-20-3963",
    money: "$155.91",
  },
  {
    fullName: "Anthiathia Valentim",
    gender: "Female",
    jobTitle: "Research Assistant IV",
    language: "Moldovan",
    ssn: "106-90-3608",
    money: "$233.58",
  },
  {
    fullName: "Elwira Sarchwell",
    gender: "Female",
    jobTitle: "Staff Accountant I",
    language: "Marathi",
    ssn: "751-73-3723",
    money: "$600.60",
  },
  {
    fullName: "Averil McClinton",
    gender: "Male",
    jobTitle: "Computer Systems Analyst III",
    language: "Amharic",
    ssn: "433-42-0777",
    money: "$912.30",
  },
  {
    fullName: "Dorolisa Durgan",
    gender: "Female",
    jobTitle: "VP Marketing",
    language: "Polish",
    ssn: "328-89-7526",
    money: "$225.23",
  },
  {
    fullName: "Fawn Lampet",
    gender: "Female",
    jobTitle: "Analog Circuit Design manager",
    language: "West Frisian",
    ssn: "236-28-5980",
    money: "$48.80",
  },
  {
    fullName: "Meriel Cashford",
    gender: "Female",
    jobTitle: "Junior Executive",
    language: "Croatian",
    ssn: "560-79-3133",
    money: "$754.92",
  },
  {
    fullName: "Rozalie Killbey",
    gender: "Female",
    jobTitle: "Professor",
    language: "Zulu",
    ssn: "612-60-6712",
    money: "$758.90",
  },
  {
    fullName: "Donnell Chetwind",
    gender: "Male",
    jobTitle: "Pharmacist",
    language: "Sotho",
    ssn: "129-43-4714",
    money: "$981.60",
  },
  {
    fullName: "Dasi Akester",
    gender: "Female",
    jobTitle: "Sales Representative",
    language: "Bulgarian",
    ssn: "659-75-9009",
    money: "$947.33",
  },
  {
    fullName: "Geri Wann",
    gender: "Female",
    jobTitle: "Programmer III",
    language: "Finnish",
    ssn: "198-70-1763",
    money: "$858.77",
  },
  {
    fullName: "Waverly Capeloff",
    gender: "Male",
    jobTitle: "Recruiter",
    language: "Arabic",
    ssn: "526-72-0377",
    money: "$394.67",
  },
  {
    fullName: "Ole Aleevy",
    gender: "Male",
    jobTitle: "Sales Representative",
    language: "Croatian",
    ssn: "520-72-2467",
    money: "$748.62",
  },
  {
    fullName: "Aprilette Odlin",
    gender: "Female",
    jobTitle: "Structural Engineer",
    language: "Luxembourgish",
    ssn: "493-86-6755",
    money: "$618.31",
  },
  {
    fullName: "Drusilla Itzkin",
    gender: "Female",
    jobTitle: "Engineer IV",
    language: "Haitian Creole",
    ssn: "682-31-3968",
    money: "$763.91",
  },
  {
    fullName: "Jerald Rennles",
    gender: "Male",
    jobTitle: "Help Desk Technician",
    language: "Ndebele",
    ssn: "569-59-1816",
    money: "$125.83",
  },
  {
    fullName: "Issie Perview",
    gender: "Female",
    jobTitle: "Account Executive",
    language: "English",
    ssn: "518-98-1869",
    money: "$177.18",
  },
  {
    fullName: "Helen-elizabeth Strugnell",
    gender: "Female",
    jobTitle: "Computer Systems Analyst IV",
    language: "Albanian",
    ssn: "327-25-5721",
    money: "$324.07",
  },
  {
    fullName: "Joanie Blundin",
    gender: "Female",
    jobTitle: "Paralegal",
    language: "Tok Pisin",
    ssn: "464-45-8000",
    money: "$882.39",
  },
  {
    fullName: "Evelina Paolone",
    gender: "Female",
    jobTitle: "Cost Accountant",
    language: "Italian",
    ssn: "455-84-5139",
    money: "$472.37",
  },
  {
    fullName: "Reinhold Ashington",
    gender: "Male",
    jobTitle: "Desktop Support Technician",
    language: "Oriya",
    ssn: "247-83-5033",
    money: "$791.07",
  },
  {
    fullName: "Stevana Ferencz",
    gender: "Female",
    jobTitle: "Statistician III",
    language: "Macedonian",
    ssn: "479-22-3719",
    money: "$401.61",
  },
  {
    fullName: "Sebastien Stollenberg",
    gender: "Male",
    jobTitle: "Senior Cost Accountant",
    language: "Belarusian",
    ssn: "650-72-4694",
    money: "$614.47",
  },
  {
    fullName: "Crichton Somerville",
    gender: "Male",
    jobTitle: "Chemical Engineer",
    language: "German",
    ssn: "737-68-7669",
    money: "$132.54",
  },
  {
    fullName: "Bo Faulks",
    gender: "Male",
    jobTitle: "Pharmacist",
    language: "Burmese",
    ssn: "170-64-5525",
    money: "$325.96",
  },
  {
    fullName: "Raf Racher",
    gender: "Female",
    jobTitle: "Executive Secretary",
    language: "English",
    ssn: "577-61-9150",
    money: "$529.76",
  },
  {
    fullName: "Donny Winchcum",
    gender: "Female",
    jobTitle: "Chemical Engineer",
    language: "Tamil",
    ssn: "663-74-9986",
    money: "$205.81",
  },
  {
    fullName: "Eirena Espinas",
    gender: "Female",
    jobTitle: "Programmer Analyst III",
    language: "Haitian Creole",
    ssn: "184-97-3977",
    money: "$866.48",
  },
  {
    fullName: "Berton Lampke",
    gender: "Male",
    jobTitle: "Paralegal",
    language: "Tetum",
    ssn: "509-50-1417",
    money: "$684.24",
  },
  {
    fullName: "Clyde Raynton",
    gender: "Male",
    jobTitle: "Chief Design Engineer",
    language: "Greek",
    ssn: "859-81-9443",
    money: "$477.69",
  },
  {
    fullName: "Clemence Hofner",
    gender: "Female",
    jobTitle: "Administrative Officer",
    language: "Croatian",
    ssn: "168-22-6201",
    money: "$530.25",
  },
  {
    fullName: "Meryl Merrgan",
    gender: "Male",
    jobTitle: "Software Engineer III",
    language: "Papiamento",
    ssn: "651-81-1806",
    money: "$35.24",
  },
  {
    fullName: "Eugen Tatlock",
    gender: "Male",
    jobTitle: "Account Representative II",
    language: "Burmese",
    ssn: "898-81-2693",
    money: "$451.83",
  },
  {
    fullName: "Darnall Koene",
    gender: "Male",
    jobTitle: "Programmer II",
    language: "Afrikaans",
    ssn: "312-12-4127",
    money: "$50.27",
  },
  {
    fullName: "Mariel Yve",
    gender: "Female",
    jobTitle: "Software Test Engineer III",
    language: "West Frisian",
    ssn: "585-66-3595",
    money: "$100.13",
  },
  {
    fullName: "Aurthur Burker",
    gender: "Male",
    jobTitle: "VP Marketing",
    language: "Somali",
    ssn: "409-71-4223",
    money: "$117.01",
  },
  {
    fullName: "Letty Garmston",
    gender: "Female",
    jobTitle: "VP Quality Control",
    language: "Oriya",
    ssn: "603-69-9215",
    money: "$850.33",
  },
  {
    fullName: "Jannelle Emmins",
    gender: "Female",
    jobTitle: "Administrative Assistant IV",
    language: "Yiddish",
    ssn: "450-37-8082",
    money: "$394.63",
  },
  {
    fullName: "Sharla Parkman",
    gender: "Female",
    jobTitle: "VP Accounting",
    language: "Dutch",
    ssn: "197-98-9502",
    money: "$797.23",
  },
  {
    fullName: "Clarence Bolwell",
    gender: "Male",
    jobTitle: "Staff Scientist",
    language: "Filipino",
    ssn: "224-66-9226",
    money: "$507.04",
  },
  {
    fullName: "Betti Fontin",
    gender: "Female",
    jobTitle: "Business Systems Development Analyst",
    language: "Tok Pisin",
    ssn: "832-24-8259",
    money: "$895.65",
  },
  {
    fullName: "Saree Defont",
    gender: "Female",
    jobTitle: "Design Engineer",
    language: "Danish",
    ssn: "349-81-4410",
    money: "$663.43",
  },
  {
    fullName: "Jess Du Barry",
    gender: "Male",
    jobTitle: "GIS Technical Architect",
    language: "Malayalam",
    ssn: "722-38-6356",
    money: "$243.90",
  },
  {
    fullName: "Lory Greenlees",
    gender: "Female",
    jobTitle: "Geological Engineer",
    language: "Norwegian",
    ssn: "875-86-1736",
    money: "$108.82",
  },
  {
    fullName: "Anallese Zeale",
    gender: "Female",
    jobTitle: "Clinical Specialist",
    language: "Portuguese",
    ssn: "189-44-8926",
    money: "$287.94",
  },
  {
    fullName: "Harlene Hazlegrove",
    gender: "Female",
    jobTitle: "Programmer III",
    language: "Dari",
    ssn: "788-36-8308",
    money: "$555.17",
  },
  {
    fullName: "Edmon Alu",
    gender: "Male",
    jobTitle: "Web Designer IV",
    language: "Bosnian",
    ssn: "460-51-4230",
    money: "$399.83",
  },
  {
    fullName: "Amelie MacDavitt",
    gender: "Female",
    jobTitle: "Senior Quality Engineer",
    language: "Nepali",
    ssn: "653-38-7906",
    money: "$819.68",
  },
  {
    fullName: "Lyndell Cheverell",
    gender: "Female",
    jobTitle: "Quality Control Specialist",
    language: "Polish",
    ssn: "457-46-1078",
    money: "$829.51",
  },
  {
    fullName: "Rudolfo Van Halle",
    gender: "Male",
    jobTitle: "Staff Scientist",
    language: "Northern Sotho",
    ssn: "340-17-5628",
    money: "$820.01",
  },
  {
    fullName: "Johannes Cicchillo",
    gender: "Male",
    jobTitle: "General Manager",
    language: "Telugu",
    ssn: "849-67-3503",
    money: "$219.92",
  },
  {
    fullName: "Wake Deeman",
    gender: "Male",
    jobTitle: "Editor",
    language: "Lithuanian",
    ssn: "745-12-9756",
    money: "$569.11",
  },
  {
    fullName: "Trey Balme",
    gender: "Male",
    jobTitle: "Research Assistant IV",
    language: "Arabic",
    ssn: "226-08-7248",
    money: "$261.96",
  },
  {
    fullName: "Blinnie Defries",
    gender: "Female",
    jobTitle: "Administrative Assistant II",
    language: "Tsonga",
    ssn: "776-20-3459",
    money: "$674.55",
  },
  {
    fullName: "Traver Halls",
    gender: "Male",
    jobTitle: "Data Coordinator",
    language: "English",
    ssn: "176-30-9227",
    money: "$40.37",
  },
  {
    fullName: "Rosabelle Yanele",
    gender: "Female",
    jobTitle: "Sales Representative",
    language: "Azeri",
    ssn: "621-77-2870",
    money: "$653.36",
  },
  {
    fullName: "Vachel McMillan",
    gender: "Male",
    jobTitle: "Data Coordinator",
    language: "Gujarati",
    ssn: "154-92-5524",
    money: "$457.86",
  },
  {
    fullName: "Valentino Damerell",
    gender: "Male",
    jobTitle: "Research Nurse",
    language: "Haitian Creole",
    ssn: "732-38-8236",
    money: "$392.34",
  },
  {
    fullName: "Odelinda Teasell",
    gender: "Female",
    jobTitle: "Senior Financial Analyst",
    language: "Bislama",
    ssn: "236-90-6595",
    money: "$318.27",
  },
  {
    fullName: "Tatum Hylton",
    gender: "Female",
    jobTitle: "VP Marketing",
    language: "English",
    ssn: "250-08-9441",
    money: "$76.10",
  },
  {
    fullName: "Sandy Edlin",
    gender: "Male",
    jobTitle: "Senior Editor",
    language: "New Zealand Sign Language",
    ssn: "858-86-7661",
    money: "$874.15",
  },
  {
    fullName: "Orlan Hudspeth",
    gender: "Male",
    jobTitle: "Help Desk Technician",
    language: "Hebrew",
    ssn: "268-86-1207",
    money: "$716.94",
  },
  {
    fullName: "Delly Bartholomieu",
    gender: "Female",
    jobTitle: "Assistant Professor",
    language: "Catalan",
    ssn: "127-70-2239",
    money: "$872.31",
  },
  {
    fullName: "Camilla Goldfinch",
    gender: "Female",
    jobTitle: "Speech Pathologist",
    language: "Aymara",
    ssn: "174-23-3028",
    money: "$542.97",
  },
  {
    fullName: "Quintus Antrobus",
    gender: "Male",
    jobTitle: "Executive Secretary",
    language: "Persian",
    ssn: "348-99-9784",
    money: "$195.43",
  },
  {
    fullName: "Deloria Crosson",
    gender: "Female",
    jobTitle: "Software Test Engineer IV",
    language: "Tswana",
    ssn: "286-85-9664",
    money: "$913.80",
  },
  {
    fullName: "Corene Bleibaum",
    gender: "Female",
    jobTitle: "Software Test Engineer I",
    language: "Indonesian",
    ssn: "731-28-9205",
    money: "$769.53",
  },
  {
    fullName: "Beryle Gippes",
    gender: "Female",
    jobTitle: "Community Outreach Specialist",
    language: "Catalan",
    ssn: "358-98-1981",
    money: "$345.44",
  },
  {
    fullName: "Nicky Beckenham",
    gender: "Female",
    jobTitle: "Physical Therapy Assistant",
    language: "Luxembourgish",
    ssn: "753-09-0880",
    money: "$56.75",
  },
  {
    fullName: "Bari Doding",
    gender: "Female",
    jobTitle: "Data Coordinator",
    language: "Oriya",
    ssn: "650-28-8400",
    money: "$579.25",
  },
  {
    fullName: "Emelda Connar",
    gender: "Female",
    jobTitle: "Health Coach IV",
    language: "French",
    ssn: "229-67-9005",
    money: "$268.54",
  },
  {
    fullName: "Gennifer Marco",
    gender: "Female",
    jobTitle: "Accounting Assistant I",
    language: "Filipino",
    ssn: "413-24-0286",
    money: "$304.41",
  },
  {
    fullName: "Griff Gowenlock",
    gender: "Male",
    jobTitle: "Assistant Professor",
    language: "English",
    ssn: "839-82-9682",
    money: "$879.44",
  },
  {
    fullName: "Jefferey Slader",
    gender: "Male",
    jobTitle: "General Manager",
    language: "Malagasy",
    ssn: "416-48-4238",
    money: "$382.63",
  },
  {
    fullName: "Tandi Merveille",
    gender: "Female",
    jobTitle: "Staff Accountant I",
    language: "Belarusian",
    ssn: "340-43-1932",
    money: "$121.67",
  },
  {
    fullName: "Nariko Zipsell",
    gender: "Female",
    jobTitle: "Physical Therapy Assistant",
    language: "Tsonga",
    ssn: "385-40-1396",
    money: "$460.63",
  },
  {
    fullName: "Tamar Geck",
    gender: "Female",
    jobTitle: "Software Test Engineer IV",
    language: "Croatian",
    ssn: "264-01-4243",
    money: "$481.69",
  },
  {
    fullName: "Lutero O'Curran",
    gender: "Male",
    jobTitle: "Database Administrator I",
    language: "Pashto",
    ssn: "590-98-7709",
    money: "$266.63",
  },
  {
    fullName: "Eugenio Kerwen",
    gender: "Male",
    jobTitle: "Administrative Assistant III",
    language: "Malagasy",
    ssn: "548-68-5295",
    money: "$694.95",
  },
  {
    fullName: "Nevsa Kulic",
    gender: "Female",
    jobTitle: "Assistant Professor",
    language: "Hindi",
    ssn: "856-40-7485",
    money: "$575.05",
  },
  {
    fullName: "Arlena Mattiato",
    gender: "Female",
    jobTitle: "Analog Circuit Design manager",
    language: "Burmese",
    ssn: "708-37-0705",
    money: "$607.25",
  },
  {
    fullName: "Amandy Matfin",
    gender: "Female",
    jobTitle: "Nuclear Power Engineer",
    language: "Luxembourgish",
    ssn: "318-91-0493",
    money: "$831.38",
  },
  {
    fullName: "Dyanna Brasner",
    gender: "Female",
    jobTitle: "Information Systems Manager",
    language: "Azeri",
    ssn: "364-70-0744",
    money: "$374.79",
  },
  {
    fullName: "Ash Feldstern",
    gender: "Male",
    jobTitle: "Web Developer II",
    language: "Malay",
    ssn: "858-19-2579",
    money: "$415.73",
  },
  {
    fullName: "Lissi Plail",
    gender: "Female",
    jobTitle: "Environmental Specialist",
    language: "Filipino",
    ssn: "613-07-4552",
    money: "$625.71",
  },
  {
    fullName: "Tawnya Castard",
    gender: "Female",
    jobTitle: "Nurse Practicioner",
    language: "Māori",
    ssn: "349-64-3914",
    money: "$568.55",
  },
  {
    fullName: "Silvain Unthank",
    gender: "Male",
    jobTitle: "Business Systems Development Analyst",
    language: "Afrikaans",
    ssn: "792-19-6916",
    money: "$258.99",
  },
  {
    fullName: "Corinna Orgel",
    gender: "Female",
    jobTitle: "Environmental Tech",
    language: "Somali",
    ssn: "215-32-4277",
    money: "$435.11",
  },
  {
    fullName: "Henry Tombs",
    gender: "Male",
    jobTitle: "Executive Secretary",
    language: "Filipino",
    ssn: "772-62-2281",
    money: "$377.72",
  },
];

//1. 풀네임에서 A, B, C로 시작하는 사람들만 남기기!
const q1 = data.filter(
  (x) =>
    x.fullName.startsWith("A") ||
    x.fullName.startsWith("B") ||
    x.fullName.startsWith("C")
);
console.log(q1);

//2. 성별이 여성이고, 풀네임이 10글자 이상인 사람만 남기기!
const q2 = data.filter((x) => x.gender == "Female" && x.fullName.length >= 10);
console.log(q2);

//3. 직업이 Manager인 사람만 남기고, 풀네임을 이름만 남기기!
const q3 = data
  .filter((x) => x.jobTitle("Manager"))
  .map((x) => (x.fullName = x.fullName.split(" ")[0]));
console.log(q3);
